.\" $Id$
.TH "iptoip.xml" "5" "February 11, 2019" "iptoip 0.3.3" "iptoip"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad
.SH "NAME"
iptoip.xml \- configuration file for iptoip
.SH "SYNOPSIS"
\fBiptoip.xml\fR
.SH "DESCRIPTION"
.PP
\fBiptoip.xml\fR is the configuration file for \fBiptoip\fR.
.PP
An XML file specifying the values \fBiptoip\fR will use to set up the IPVS
table. This stored configuration persists across reboots or IP address changes.
.LP 
It may look as follows:
.IP 
.nf 
<config>
	<iface>ppp0</iface>
	<nocheck>0</nocheck>
	<rfc1918>2</rfc1918>
	<verbose>1</verbose>
	<syslog>1</syslog>
	<logfile>/var/log/iptoip.log</logfile>

	<conf>
		<origin>192.168.1.1</origin>
		<scheduler>wlc</scheduler>
		<destination>192.168.1.3</destination>
		<protocol>u</protocol>
		<weight>5</weight>
		<port>80</port>
		<port>21</port>
	</conf>

	<conf>
		<origin>192.168.1.1</origin>
		<protocol>t</protocol>
		<scheduler>wrr</scheduler>
		<weight>10</weight>
		<port>6000</port>
	</conf>
</config>
.fi 
.SH "XML ENTRIES"
Here are the supported tags :
.br
A trailing \fB*\fR denotes required tags.
.TP 
.B "<config>"*
Begin the config file. This block contains global config values and VE
( Virtual Entity ) definitions.
.TP 
.B "<iface>"*
VE service interface (ppp0, eth0...). The IP address of this interface is the
default VE service IP.
.TP 
.B "<nocheck> "DEPRECATED
1/0 ; Disable/Enable interface \fIRFC1918\fR check.
\fBWill be removed in future release.\fR
.TP 
.B "<rfc1918>"
Block setup of VE service IP in \fIRFC1918\fR address space.
.br
0 ; Don't block.
.br
1 ; Block Interface.
.br
2 ; Block Interface & Origin tags.
.br
Defaults to 2 if not specified in \fB\iptoip.xml\fR.
.TP 
.B "<verbose>"*
1/0 ; Enable/disable on screen startup report.
.TP 
.B "<syslog>"*
1/0 ; Enable/disable Logging to syslog facility.
.br
Enabling syslog overrides <logfile>
.TP 
.B "<logfile>"
path/file ; Log to file.
.TP 
.B "<conf>"
Start VE ( Virtual Entity ) definition.
.br
A trailing \fB**\fR denotes required VE definition tags.
.TP 
.B "<origin>"
IP address ; Specify alternate VE service IP. This VE will service requests on
the specificed IP, \fBnot\fR the default VE service IP.
.TP 
.B "<protocol>"**
Set VE service protocol.
.br
t ; TCP.
.br
u ; UDP.
.br
a ; TCP & UDP.
.TP
.B "<scheduler>"**
text ; VE scheduler.
.br
Any scheduler supported by the LVS ( Linux Virtual Server ) kernel system.
.br
Currently:
.br
rr|wrr|lc|wlc|lblc|lblcr|dh|sh|sed|nq ;
.br
See \fBipvsadm\fR(8) for more info.
.TP 
.B "<destination>"**
IP address ; The IP of the VE server.
.TP 
.B "<weight>" 
number 0-65535 ; The "weight" of the VE server. Higher weights denote a more
powerful server.
.br
Defaults to 1 if not specified in \fB\iptoip.xml\fR.
.br
Only used with the wrr and wlc schedulers.
.TP 
.B "<port>"**
number 0-65535 ; VE service port.
.TP 
.B "<forward>"
Set VE packet forwarding method.
.br
masq ; Use masquerading (network access translation, or NAT).
.br
gate ; Use gatewaying (direct routing).
.br
tunl ; Use ipip encapsulation (tunneling).
.br
Defaults to masq if not specified in \fB\iptoip.xml\fR.

.SH "AUTHORS"
Lenny Cartier.
.br
Nathan Gibbs.
.SH "REPORTING BUGS"
Please submit at: https://github.com/lennycartier/iptoip/issues
.SH "COPYRIGHT"
Copyright \(co 2001 Lenny Cartier.
.br
Copyright \(co 2013-2019 Nathan Gibbs.
.br
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE;
Licensed under the General Public License (GPL).
.SH "FILES"
.PP
\fI/etc/iptoip.xml\fR
.SH "SEE ALSO"
The LVS web site. http://www.linuxvirtualserver.org
.PP
\fBiptoip\fR(8), \fBipvsadm\fR(8), the LVS\-HOWTO.
.PP
DARPA Internet Request For Comments
.IR RFC1918 .
