.\" $Id$
.TH iptoip "8" "December 28, 2018" "iptoip 0.3.2"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH NAME
iptoip \- IPVS table setup utility
.SH SYNOPSIS
\fBiptoip\fR [\fB\-f\ \fR\fB\fIconfig\-file\fR\fR] [\fB\-h\fR]
.SH DESCRIPTION
.PP
\fBiptoip\fR is a tool designed to setup and maintain the IPVS table on Linux
hosts.
.PP
Written in perl and using an XML configuration file in conjunction with the
\fBipvsadm\fR(8) tool, \fBiptoip\fR maintains the IPVS table configuration across
reboots or IP address changes.
.br
Useful for maintaining an IPVS table on a dynamic IP address or intermittent
connection.
.PP
When invoked without arguments,
\fBiptoip\fR
will read the default configuration file
\fI/etc/iptoip.xml\fR, and setup the IPVS table.
.SH "OPTIONS"
.TP
\fB\-f | -\-file\fR \fB\fIconfig\-file\fR
Use
\fIconfig\-file\fR
as the configuration file instead of the default,
\fI/etc/iptoip.xml\fR.
.TP
\fB\-h | -\-help\fR
Show help message and exits.
.SH AUTHORS
Lenny Cartier.
.br
Nathan Gibbs.
.SH "REPORTING BUGS"
Report bugs to <nathan@cmpublishers.com>.
.SH COPYRIGHT
Copyright \(co 2001 Lenny Cartier.
.br
Copyright \(co 2013-2018 Nathan Gibbs.
.br
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE;
Licensed under the General Public License (GPL).
.SH FILES
.PP
\fI/etc/iptoip.xml\fR
.RS 4
The default configuration file.
.RE
.SH "SEE ALSO"
The LVS web site (http://www.linuxvirtualserver.org/) for more
documentation about LVS.
.PP
\fBiptoip.xml\fR(5), \fBipvsadm\fR(8), the LVS\-HOWTO.
